name: Track Noir Downloads

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  track-downloads:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib
    
    - name: Run download tracker
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: python scripts/nargo_download_tracker.py
    
    - name: Generate visualizations
      run: python scripts/visualize_downloads.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv *.json
        git add *.png
        git diff --quiet && git diff --staged --quiet || git commit -m "Update download statistics and visualizations
        git push